### PR TITLE
fix issue 1

### PR DESCRIPTION
**Pull request by bkfox**
Fix issue #1 

This needs the fix of issue 1 of libfastcal

### CODE REVIEW

**Comment by sflotron** [comment]
Thanks for your proposition of improvement and your remarks about the code.

However, libfastcal will stay in pure C, and consequently your remark about it won't be considered. Moreover, I don't want to add libboost as a dependency in order to check the 4 input argument of the software. Could you modify your pull request to take these informations into your pull request ?

**Comment by bkfox** [comment]
I'll do it asap.

For libfastcall, at least using const signed char seems for me the best option, regarding arguments developed in issue FoxelSA/libfastcal#1 about this specific element.

**Comment by sflotron** [comment]
Ok, thanks for your removal of lib boost. 

However I see a lot of auto in your code, this is unsafe, because it can lead to unsecure type affectation. In my opinion, the only good usage of auto would be in case of template, which is clearly not the case here. So I ask yout to remove these calls to auto.

Second thing, imread and imwrite does not do padding of image, which can lead to bugs or worse perfomances, see following link. http://answers.opencv.org/question/20407/matstep-iplimagewidthstep/. So I want to keep class Ipl image in gnoproj, since we are using opencv 3.0

**Comment by sflotron** [comment]
By the way, if you could make a comment to inform me that you have made the asked modification, it would be top !

**Comment by bkfox** [comment]
Well I don't have OpenCV 3.0 in my repo, so can not adapt it. Is there a C++ API for IPl? Furthermore, I've started a bit digging about that: http://stackoverflow.com/questions/5192578/opencv-iplimage ;

About auto: using auto does not lead to insecure type affection. Compiler determine to the type at compilation (depending on the variable initializer), and then apply the same casting rules for the determined type (in general, the defaults implicit casting are really limited, and those that can lead to undefined behaviors cause warning from compiler). The potential problem of auto is the documentation about the type used or required elements on it.

**Comment by sflotron** [comment]
Ok for the auto,  I can keep it in my code, although I really do not like the usage of it, because using auto can make the programmer forget the type of its variable. 
Nevertheless, I still want to use Ipl images, so if you could revert some of your modifications in order to use it, it would be nice !

**Comment by sflotron** [comment]
First, the software is not compiling, I have to add header to make it compile. Moreover, the software is not running, it get the folllowing error message

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul
Abandon (core dumped)

So the pull request will be rejected

**Comment by bkfox** [comment]
Argument error fixed (stoul exception). About compiling there was no problem when I built it.

**Pull request closed without merging**
